tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - modules/openstack/openstack_vm.yaml
  - modules/docker/docker_host.yaml
  - modules/docker/docker_network.yaml
  - modules/docker/docker_registry.yaml
  - modules/docker/docker_component.yaml
# - modules/docker/docker_certificate.yaml
  - modules/misc/ssh/types.yaml
  - library/hpc-exporter/ssh-key-config.yaml

node_types:

  sodalite.nodes.SodaliteVM:
    derived_from: tosca.nodes.Compute
    properties:
      username:
        type: string

topology_template:

  inputs:
    username:
      type: string
    docker-network:
      type: string
    ssh-key-file-path:
      type: string
    hpc-exporter-env:
      type: map

  node_templates: 

    sodalite-vm:
      type: sodalite.nodes.SodaliteVM
      properties:
        username: { get_input: username }
      attributes:
        private_address: localhost
        public_address: localhost

    docker-host:
      type: sodalite.nodes.DockerHost
      requirements:
        - host: sodalite-vm

    docker-network:
      type: sodalite.nodes.DockerNetwork
      properties:
        name: { get_input: docker-network }
      requirements:
        - host: sodalite-vm
        - dependency: docker-host

    docker-local-registry:
      type: sodalite.nodes.DockerRegistry
      properties:  
        docker_registry_url: localhost:5555
      requirements:
        - host: sodalite-vm
        - dependency: docker-host

    monitoring-system-hpc-exporter-ssh-key-config:
      type: sodalite.nodes.monitoring-system-hpc-exporter.config
      properties:
        ssh-key-file-path: { get_input: ssh-key-file-path }
 
    monitoring-system-hpc-exporter:
      type: sodalite.nodes.DockerizedComponent
      properties:
        image_name: hpc-exporter
        restart_policy: "no"
#       ports: ['9100:9100']
#       exposed_ports:  ['9100']
        docker_network_name:  { get_property: [ SELF, network, name ] }
        env: { get_input: hpc-exporter-env }
        volumes:
          - "/tmp/ssh-key:/app/ssh_key"
        alias: hpc-exporter
      requirements:
        - host: sodalite-vm
        - network: docker-network
        - registry: docker-local-registry
        - dependency: monitoring-system-hpc-exporter-ssh-key-config
