tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - modules/openstack/openstack_vm.yaml
  - modules/docker/docker_host.yaml
  - modules/docker/docker_network.yaml
  - modules/docker/docker_registry.yaml
  - modules/docker/docker_component.yaml
  - modules/misc/ssh/types.yaml
  - library/hpc-exporter/ssh-key-config.yaml

node_types:

  sodalite.nodes.SodaliteVM:
    derived_from: tosca.nodes.Compute
    properties:
      username:
        type: string

topology_template:

  inputs:
    username:
      type: string
    docker-network:
      type: string
    docker-public-registry-url:
      type: string
    ssh-key-file-path:
      type: string
    hpc-exporter-env:
      type: map

  node_templates: 

    sodalite-vm:
      type: sodalite.nodes.SodaliteVM
      properties:
        username: { get_input: username }
      attributes:
        private_address: localhost
        public_address: localhost

    docker-host:
      type: sodalite.nodes.DockerHost
      requirements:
        - host: sodalite-vm

    docker-network:
      type: sodalite.nodes.DockerNetwork
      properties:
        name: { get_input: docker-network }
      requirements:
        - host: sodalite-vm
        - dependency: docker-host

    docker-public-registry:
      type: sodalite.nodes.DockerRegistry
      properties:  
        docker_registry_url: { get_input: docker-public-registry-url } 
      requirements:
        - host: sodalite-vm
        - dependency: docker-host
 
    monitoring-system-hpc-exporter:
      type: sodalite.nodes.DockerizedComponent
      properties:
        image_name: sodaliteh2020/hpc-exporter:latest
        restart_policy: "no"
        ports: [ '9110:9110' ]
        exposed_ports: [ '9110' ]
        docker_network_name:  { get_property: [ SELF, network, name ] }
        alias: hpc-exporter
      requirements:
        - host: sodalite-vm
        - network: docker-network
        - registry: docker-public-registry
