tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  sodalite.nodes.monitoring-system-hpc-exporter.config:
    derived_from: tosca.nodes.SoftwareComponent
    description: Node for recreation of SSH key file in a temporary folder
    properties:
      ssh-key-file-path:
        type: string
        description: Absolute path of SSH key file to copy
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          create:
            inputs:
              ssh_key_file_path: { default: { get_property: [ SELF, ssh-key-file-path ] }, type: string }
            implementation:
              primary: playbooks/ssh_key_copy.yml

